### ISSUE TITLE
No sql file

### ISSUE THREAD

**Issue by NaysKutzu** [Roskus/lpanel#2]

**Comment by gnovaro** [comment]
Laravel comes with a feature call migrations,

Just run
```console
php artisan migrate 
```

i will review the install command

**Comment by NaysKutzu** [comment]
Ye I found that, but it does not have a lot of things inside it like file manager etc. and it does not have a well written documentation

**Comment by gnovaro** [comment]
Take in consideration i do it in my free time, but for file manager, exist others tools you can integrate, always you can open a pull request
